/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.18).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package pro.cvitae.gmailrelayer.api;

import java.util.Optional;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;

import com.fasterxml.jackson.databind.ObjectMapper;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.model.EmailMessage;
import io.swagger.model.ErrorDetail;
import io.swagger.model.SendEmailResult;

@Api(value = "mail")
public interface MailApi {

    default Optional<ObjectMapper> getObjectMapper() {
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest() {
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return this.getRequest().map(r -> r.getHeader("Accept"));
    }

    @ApiOperation(value = "sends an email", nickname = "sendEmail", notes = "Sends an email with the specified data", response = SendEmailResult.class)
    @ApiResponses(value = { @ApiResponse(code = 200, message = "email sent", response = SendEmailResult.class),
            @ApiResponse(code = 202, message = "email queued for later delivery", response = SendEmailResult.class),
            @ApiResponse(code = 400, message = "invalid input", response = ErrorDetail.class),
            @ApiResponse(code = 401, message = "unauthorized", response = ErrorDetail.class) })
    default ResponseEntity<SendEmailResult> sendEmail(
            @ApiParam(value = "Email to be sent", required = true) @Valid @RequestBody final EmailMessage body) {
        throw new UnsupportedOperationException("Not implemented");
    }

}
